=== Deandun/NINARow/NINARow/out/production/NINARow/resources/NinaRow.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by mazuki (darksiderg) -->
<!--W3C Schema generated by XMLSpy v2008 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="GameDescriptor">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="GameType">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="Basic"/>
							<xs:enumeration value="MultiPlayer"/>
							<xs:enumeration value="DynamicMultiPlayer"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element ref="Game"/>
				<xs:element ref="Players" minOccurs="0"/>
				<xs:element ref="DynamicPlayers" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Type">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Computer"/>
				<xs:enumeration value="Human"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Players">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Player" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Player">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Name"/>
				<xs:element ref="Type"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:short" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Name">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Game">
		<xs:complexType>
			<xs:all>
				<xs:element ref="Board"/>
				<xs:element name="Variant">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="Regular"/>
							<xs:enumeration value="Popout"/>
							<xs:enumeration value="Circular"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:all>
			<xs:attribute name="target" type="xs:integer" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="DynamicPlayers">
		<xs:complexType>
			<xs:attribute name="total-players" type="xs:byte" use="required"/>
			<xs:attribute name="game-title" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Board">
		<xs:complexType>
			<xs:attribute name="rows" type="xs:byte" use="required"/>
			<xs:attribute name="columns" type="xs:integer" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Deandun/NINARow/master.xml
<?xml version="1.0" encoding="UTF-8"?>
<GameDescriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="NinaRow.xsd">
	<GameType>Basic</GameType>
	<Game target="4">
		<Board rows="6" columns="7"/>
		<Variant>Regular</Variant>
	</Game>
	<Players>
		<Player id="233">
			<Name>Mushon</Name>
			<Type>Human</Type>
		</Player>
		<Player id="143">
			<Name>Menash</Name>
			<Type>Human</Type>
		</Player>
	<DynamicPlayers game-title="sample game" total-players="3"/>
</GameDescriptor>
